services:
  app:
      container_name: taskmanager_app
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task-manager
        SPRING_DATASOURCE_USERNAME: tm_user
        SPRING_DATASOURCE_PASSWORD: tm_password
      ports:
        - "8080:8080"
      networks:
        - tm_network
      depends_on:
        - db

  db:
    container_name: taskmanager_db
    image: postgres
    environment:
      POSTGRES_USER: tm_user
      POSTGRES_PASSWORD: tm_password
      POSTGRES_DB: task-manager
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db:/data/postgres
    networks:
      - tm_network

networks:
  tm_network:
    driver: bridge

volumes:
  db: