apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taskmanager-chart.fullname" . }}-postgres-pvc
  labels:
    {{- include "taskmanager-chart.labels" . | nindent 4 }}
    app: postgres
    tier: database
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  accessModes:
    - ReadWriteOnce   
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | default "1Gi" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskmanager-chart.fullname" . }}-postgres
  labels:
    {{- include "taskmanager-chart.labels" . | nindent 4 }}
    app: postgres
    tier: database
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
spec:
  selector: 
    matchLabels:
      app: postgres
      tier: database
      {{- include "taskmanager-chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: postgres
        tier: database
        {{- include "taskmanager-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskmanager-chart.fullname" . }}-pg-secrets
                  key: db_username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskmanager-chart.fullname" . }}-pg-secrets
                  key: db_password

            - name: POSTGRES_DB 
              valueFrom:
                configMapKeyRef:
                  name: {{ include "taskmanager-chart.fullname" . }}-db-config
                  key: db_name

          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:       
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
          {{- with .Values.database.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postgres-persistent-storage 
          persistentVolumeClaim:
            claimName: {{ include "taskmanager-chart.fullname" . }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager-chart.fullname" . }}-postgres
  labels:
    {{- include "taskmanager-chart.labels" . | nindent 4 }}
    app: postgres
    tier: database
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:       
    app: postgres
    tier: database
    {{- include "taskmanager-chart.selectorLabels" . | nindent 4 }}
  clusterIP: None 